
const menuList = [
    {
        title:'首页',
        key:'/home',
        icon:'home',
    },
    {
        title:'基础内容',
        key:'/base',
        icon:'global',
        children:[
            {
                title:'站点信息',
                key:'/base/site',
                icon:'',
            },
            {
                title:'公司信息',
                key:'/base/company',
                icon:'',
            },
        ]
    },
    {
        title:'内容管理',
        key:'/content',
        icon:'appstore-o',
        children:[
            {
                title:'文章分类',
                key:'/content/articleSort',
                icon:'',
            },
            {
                title:'文章管理',
                key:'/content/article',
                icon:'',
            },
            {
                title:'轮播图片',
                key:'/content/banner',
                icon:'',
            },
            {
                title:'专题管理',
                key:'/content/special',
                icon:'',
            },
        ]
    },
    {
        title:'扩展内容',
        key:'/extend',
        icon:'paper-clip',
        children:[
            {
                title:'友情链接',
                key:'/extend/friendLink',
                icon:'',
            },
            {
                title:'广告投放',
                key:'/extend/adServer',
                icon:'',
            },
        ]
    },
    {
        title:'组织管理',
        key:'/organization',
        icon:'usergroup-add',
        children:[
            {
                title:'部门管理',
                key:'/organization/department',
                icon:'',
            },
            {
                title:'用户管理',
                key:'/organization/user',
                icon:'',
            },
        ]
    },
    {
        title:'消息管理',
        key:'/notify',
        icon:'notification',
        children:[
            {
                title:'系统公告',
                key:'/notify/systemBulletin',
                icon:'',
            },
            {
                title:'网站留言',
                key:'/notify/websiteMessage',
                icon:'',
            },
        ]
    },
    {
        title:'系统管理',
        key:'/setting',
        icon:'setting',
        children:[
            {
                title:'个人中心',
                key:'/setting/personal',
                icon:'',
            },
            {
                title:'系统用户',
                key:'/setting/admin',
                icon:'',
            },
            {
                title:'角色配置',
                key:'/setting/post',
                icon:'',
            },
            {
                title:'操作日志',
                key:'/setting/log',
                icon:'',
            },
        ]
    },
]

export default menuList;